const assert = require("assert");
const fs = require("fs");

const html = fs.readFileSync("index.html", "utf8");
const css = fs.readFileSync("styles.css", "utf8");
const app = fs.readFileSync("app.js", "utf8");

const brandBlock = html.match(/<section class="brand-block">([\s\S]*?)<\/section>/)?.[1] || "";
const clockBlock = html.match(/<section class="clock-block"[\s\S]*?>([\s\S]*?)<\/section>/)?.[1] || "";
const holidayCard = html.match(/<section class="holiday-card"[\s\S]*?>([\s\S]*?)<\/section>/)?.[1] || "";
const topActions = html.match(/<header class="top-actions">([\s\S]*?)<\/header>/)?.[1] || "";
const bookingModal = html.match(/<dialog id="booking-modal"[\s\S]*?<\/dialog>/)?.[0] || "";
const schedulePreviewModal = html.match(/<dialog id="schedule-preview-modal"[\s\S]*?<\/dialog>/)?.[0] || "";
const detailModal = html.match(/<dialog id="detail-modal"[\s\S]*?<\/dialog>/)?.[0] || "";
const legendBlock = css.match(/\.timeline-card \.legend\s*{([^}]*)}/)?.[1] || "";
const currentTimeBlock = css.match(/\.current-time\s*{([^}]*)}/)?.[1] || "";
const dateLineBlock = css.match(/\.date-line\s*{([^}]*)}/)?.[1] || "";
const requiredIconFiles = ["clock-3", "info", "calendar-days", "users", "monitor", "video", "wifi"];
const summaryTitles = ["next-meeting-title", "room-details-title", "availability-title"].map((id) => {
  const match = html.match(new RegExp(`<h2 id="${id}">([^<]+)<\\/h2>`));
  return match?.[1] || "";
});

assert.ok(!html.includes("modify-booking-btn"), "modify booking button should be removed");
assert.ok(brandBlock.includes('id="data-menu-btn"'), "settings button should live in the brand block");
assert.ok(!topActions.includes('id="data-menu-btn"'), "settings button should not be in right top actions");
assert.ok(
  brandBlock.indexOf('id="data-menu-btn"') < brandBlock.indexOf('id="app-name"'),
  "settings button should appear before the AI英雄汇 title"
);
assert.ok(topActions.includes('id="book-room-btn"'), "book room button should remain in top actions");
assert.ok(topActions.includes('id="schedule-preview-btn"'), "schedule preview entry should be next to booking actions");
assert.ok(detailModal.includes('id="detail-list"'), "detail modal should expose a replaceable detail list for grouped bookings");
assert.ok(schedulePreviewModal.includes("Schedule Preview / 日程预览"), "schedule preview modal should exist");
assert.ok(schedulePreviewModal.includes('id="week-view-btn"') && schedulePreviewModal.includes('id="agenda-view-btn"'), "schedule preview should support week and agenda views");
assert.ok(schedulePreviewModal.includes('id="week-grid"') && schedulePreviewModal.includes('id="agenda-list"'), "schedule preview should include week grid and agenda list containers");
assert.ok(schedulePreviewModal.includes('id="preview-week-range-text"'), "schedule preview range should have a dedicated text span for a calendar-icon layout");
const nextWeekButton = html.match(/<button id="preview-next-week"[\s\S]*?<\/button>/)?.[0] || "";
assert.ok(nextWeekButton.indexOf('class="preview-nav-copy"') < nextWeekButton.indexOf('class="preview-nav-icon"'), "next-week button should place the arrow icon after the text");
assert.ok(bookingModal.includes("Availability on Selected Date / 所选日期可用状态"), "booking modal should show selected-date availability preview");
assert.ok(bookingModal.includes('id="booking-availability-timeline"') && bookingModal.includes('id="booking-time-feedback"'), "booking modal should include live availability timeline and feedback");
assert.ok(!clockBlock.includes("CURRENT TIME / 当前时间"), "left clock block should not show a redundant current-time label");
assert.match(currentTimeBlock, /font-size:\s*clamp\(3\.15rem,\s*4\.35vw,\s*4\.25rem\);/, "left clock time should use a smaller display size");
assert.match(dateLineBlock, /font-size:\s*clamp\(0\.78rem,\s*1\.02vw,\s*0\.95rem\);/, "left clock date text should be smaller than before");
assert.deepStrictEqual(summaryTitles, ["NEXT MEETING", "ROOM DETAILS", "AVAILABILITY"], "summary card English titles should not include slash separators when Chinese titles sit on the next line");
for (const icon of requiredIconFiles) {
  assert.ok(fs.existsSync(`assets/icons/${icon}.svg`), `downloaded Lucide icon should exist offline: ${icon}`);
  assert.ok(html.includes(`id="icon-${icon}"`), `inline icon sprite should include ${icon}`);
}
assert.ok(!html.includes(">◴<") && !html.includes(">ⓘ<"), "summary card icons should use SVG instead of font glyphs");
assert.ok(!html.includes('class="card-icon blue">▣'), "availability card icon should use SVG instead of a font glyph");
assert.ok(!holidayCard.includes("▣"), "holiday card title icon should use SVG instead of a square font glyph");
assert.ok(holidayCard.includes('<svg class="ui-icon"') && holidayCard.includes('href="#icon-calendar-days"'), "holiday card title icon should use a semantic calendar SVG icon");
assert.ok(app.includes("https://date.nager.at/api/v3/PublicHolidays"), "holiday card should use a real public-holiday API source");
assert.ok(app.includes('code: "MY"') && app.includes('code: "CN"'), "default holiday countries should include Malaysia and China");
assert.ok(app.includes("nager-date"), "normalized holiday data should record the real API source");
assert.ok(!html.includes("import-data-input"), "settings modal should not expose an import control");
assert.ok(!html.includes("Import Data / 导入数据"), "settings modal should not include an import action");
assert.ok(!app.includes("function importData"), "app should not keep JSON import behavior");
assert.ok(html.includes("Export Meeting Records / 导出会议记录"), "settings modal should export meeting records only");
assert.ok(app.includes("exportMeetingRecords"), "export action should target meeting records instead of full app data");
assert.ok(!app.includes("roomConfig: loadRoomConfig()"), "meeting-record export should not include room configuration");
assert.ok(!app.includes("holidayCache: loadHolidayCache()"), "meeting-record export should not include holiday cache data");
assert.ok(!app.includes('"♙"') && !app.includes('"▣"') && !app.includes('"▤"') && !app.includes('"⌁"'), "room detail feature icons should use SVG instead of font glyphs");
assert.ok(app.includes("feature-icon") && app.includes('href="#icon-${iconId}"'), "room detail feature icons should render Lucide SVG symbols");
assert.ok(app.includes('"users"') && app.includes('"monitor"') && app.includes('"video"') && app.includes('"wifi"'), "room detail feature icons should map to semantic Lucide icons");
assert.match(css, /\.card-icon \.ui-icon\s*{[\s\S]*width:\s*clamp\(1rem,\s*1\.25vw,\s*1\.12rem\);/, "summary card icon SVGs should have a controlled size");
assert.match(css, /\.schedule-preview-modal\s*{[\s\S]*width:\s*min\(92rem,\s*calc\(100vw - 5rem\)\);/, "schedule preview modal should use the wide reference-style canvas");
assert.match(css, /\.schedule-preview-panel\s*{[\s\S]*padding:\s*clamp\(2rem,\s*3vw,\s*2\.6rem\);/, "schedule preview panel should use generous reference-style padding");
assert.match(css, /\.schedule-preview-header h2\s*{[\s\S]*font-size:\s*clamp\(1\.65rem,\s*2vw,\s*2\.1rem\);/, "schedule preview title should be prominent");
assert.match(css, /\.preview-toolbar\s*{[\s\S]*grid-template-columns:\s*minmax\(24rem,\s*1fr\)\s*auto\s*minmax\(24rem,\s*1fr\);/, "schedule preview toolbar should keep nav, range, and view switch aligned");
assert.match(css, /\.preview-nav-btn\s*{[\s\S]*min-width:\s*clamp\(6rem,\s*7\.4vw,\s*8\.9rem\);/, "schedule preview nav buttons should shrink without forcing toolbar overflow");
assert.match(css, /\.preview-view\s*{[\s\S]*height:\s*min\(58vh,\s*31rem\);/, "schedule preview views should share one fixed content height");
assert.match(css, /\.week-grid\s*{[\s\S]*grid-template-columns:\s*4\.25rem repeat\(5,\s*minmax\(10rem,\s*1fr\)\);/, "week grid should give day columns enough room for readable text");
assert.match(css, /\.week-grid\s*{[\s\S]*height:\s*100%;/, "week view should fill the shared fixed preview height");
assert.match(css, /\.agenda-list\s*{[\s\S]*height:\s*100%;/, "agenda view should fill the shared fixed preview height");
assert.match(css, /\.agenda-list\s*{[\s\S]*overflow-y:\s*auto;/, "agenda view should scroll vertically when content exceeds the fixed height");
assert.match(css, /\.agenda-list\s*{[\s\S]*overflow-x:\s*hidden;/, "agenda view should avoid horizontal overflow inside the fixed height");
assert.match(css, /\.preview-nav-btn\.next\s*{[\s\S]*justify-content:\s*space-between;/, "next-week button should keep text and right arrow visually symmetric");
assert.ok(!app.includes("week-current-line"), "week view should not render a current-time indicator line");
assert.ok(!css.includes(".week-current-line"), "week view should not style a current-time indicator line");
assert.ok(!app.includes("week-booking-time") && !app.includes("week-booking-booker"), "week booking blocks should not render visible text content");
assert.ok(app.includes("week-time-label end"), "week time axis should mark the final hour label to prevent bottom clipping");
assert.match(css, /\.week-time-label\.end\s*{[\s\S]*transform:\s*translateY\(-100%\);/, "final week time label should sit fully inside the grid");
assert.match(css, /\.week-booking\s*{[\s\S]*min-height:\s*0;/, "week booking blocks should allow compact adjacent color marks");
assert.match(css, /\.week-booking\s*{[\s\S]*padding:\s*0;/, "week booking color marks should not reserve text padding");
assert.match(css, /\.week-booking\s*{[\s\S]*font-size:\s*0;/, "week booking color marks should not show text");
assert.ok(app.includes("getMergedWeekBookingBlocks"), "week view should merge adjacent bookings before rendering occupied blocks");
assert.ok(app.includes("data-booking-ids"), "merged week booking blocks should carry all source booking ids");
assert.ok(app.includes("openBookingGroupDetailModal"), "merged week booking block clicks should open grouped booking details");
assert.match(css, /\.detail-group\s*{[\s\S]*display:\s*grid;/, "grouped booking details should use a readable stacked layout");
assert.ok(!app.includes("bookingGap"), "week booking blocks should not leave gaps between adjacent meetings");
assert.match(css, /\.week-booking\s*{[\s\S]*left:\s*0;/, "week booking occupied blocks should fill the full day column width");
assert.match(css, /\.week-booking\s*{[\s\S]*right:\s*0;/, "week booking occupied blocks should fill the full day column width");
assert.match(css, /\.week-booking\s*{[\s\S]*border-radius:\s*0;/, "week booking occupied blocks should align with the grid instead of floating like pills");
assert.match(css, /\.week-booking\s*{[\s\S]*background:\s*linear-gradient\(180deg,\s*#2f89f5,\s*#1972e8\);/, "week booking blocks should use a grid-cell fill treatment");
assert.match(css, /\.agenda-item\s*{[\s\S]*grid-template-columns:\s*11rem minmax\(0,\s*1fr\)\s*minmax\(14rem,\s*20rem\);/, "agenda rows should reserve readable columns for time, meeting, and booker");
assert.match(css, /\.booking-availability\s*{[\s\S]*border:/, "booking availability preview should have a distinct panel");
assert.match(css, /\.booking-availability-wrap\s*{[\s\S]*margin-bottom:\s*1\.95rem;/, "booking modal availability timeline should reserve enough room for the current-time pointer label");
assert.match(css, /\.booking-current-pointer span\s*{[\s\S]*top:\s*calc\(100% \+ 0\.28rem\);/, "booking modal current-time label should sit below the timeline to avoid axis-label overlap");
assert.match(css, /\.booking-current-pointer span\s*{[\s\S]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.92\);/, "booking modal current-time label should have a readable backing");
assert.match(css, /\.booking-availability-legend\s*{[\s\S]*margin-top:\s*0;/, "booking modal availability legend should rely on timeline spacing instead of a collapsing top margin");
assert.ok(!css.includes("@media (max-width"), "mobile breakpoint layouts should be removed");
assert.match(css, /\.app-shell\s*{[\s\S]*height:\s*100dvh;/, "app shell should fit one dynamic viewport");
assert.ok(css.includes("@media (max-aspect-ratio"), "layout should adapt to narrower display ratios");
assert.ok(css.includes("@media (max-height"), "layout should compact on shorter displays");
assert.match(css, /\.schedule-card\s*{[\s\S]*min-height:\s*0;/, "schedule card should not force overflow");
assert.match(css, /\.schedule-card\s*{[^}]*overflow-y:\s*auto;/, "schedule card should scroll vertically when many meetings are listed");
assert.match(css, /\.schedule-table th\s*{[^}]*position:\s*sticky;/, "schedule table header should stay visible while scrolling");
assert.match(css, /\.info-card\s*{[\s\S]*min-height:\s*0;/, "summary cards should not force tall blanks");
assert.match(css, /\.info-card\s*{[\s\S]*height:\s*100%;/, "summary cards should share one equal height");
assert.match(css, /\.info-grid\s*{[\s\S]*align-items:\s*stretch;/, "summary card grid should stretch all cards equally");
assert.match(css, /\.main-panel\s*{[\s\S]*grid-template-rows:[\s\S]*50vh[\s\S]*31vh/, "main panel should give the schedule more height before the summary cards");
assert.match(css, /\.status-panel\s*{[\s\S]*display:\s*block;/, "status panel should use reference-style anchored vertical proportions");
assert.match(css, /\.timeline-card\s*{[\s\S]*overflow:\s*hidden;/, "availability card should contain its own content");
assert.match(legendBlock, /grid-template-columns:/, "availability legend should be constrained inside the card");
assert.match(legendBlock, /grid-auto-flow:\s*column;/, "availability legend should prefer one row");
assert.match(legendBlock, /justify-content:\s*space-between;/, "availability legend should distribute labels across the full timeline width");
assert.match(legendBlock, /white-space:\s*nowrap;/, "availability legend labels should stay on one line");

console.log("Layout structure tests passed.");
